rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

env:
  - DB=sqlite
  - DB=mysql

before_script: ruby ./script/ci/travis_before_build.rb
script: bundle exec rake db:drop db:create db:migrate test RAILS_ENV=test

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
